draf2/draf2/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('draftapp/', include('draftapp.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path("silk/", include("silk.urls", namespace="silk")),
]

draf2/draftapp/urls.py
from django.urls import path, re_path
from . import views


app_name = "draftapp"
urlpatterns = [
    #/draftapp/
    path('', views.IndexView, name = 'index'),  #app homepage
    path('Gwas_search_extended/', views.gwas_search_extended, name = 'gwas_search_extended'),
    path('Gwas_search_extended/Gwas_result/', views.gwas_search_results_dict_2, name = 'Gwas_search_results_dict'),
    path('Snp_search/', views.snp_search, name = 'snp_search'),
    path('Snp_detail/<pk>/', views.SnpsDetailView.as_view(), name = 'snp_detail'),
    path('Snp_search/Snp_results/', views.snp_search_results, name = 'snp_search_results'),
    path('Gene_search/', views.gene_search, name = 'gene_search'),
    path('Gene_search/Gene_result/', views.gene_search_results_snps, name = 'gene_search_results'),
    path('REST_API/', views.REST_API_view, name = "REST_API"),
    path('REST_API/snps/<pk>/', views.snps_detail),
    path('REST_API/GWASQuery/<pk>/', views.GWASQueryRESTAPIview),
    path('REST_API/GeneQuery/<genes>/', views.GeneQueryRESTAPIview)
 ]

draf2/draftapp/views.py
from django.shortcuts import render
from django.views import generic
from .models import Interactionsxgenexsnps, Snps, Gwasinfo, Tfs, Tfsxsnps, Geneannotation, Gwasinfo
from django.http import Http404
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from draftapp.serializers import SnpsSerializer, GwasDictSerializer, GeneDictSerializer
import json
from .GWASQuery import *


# Create your views here.
def IndexView(request):
    return render(request, 'draftapp/index.html')
    



def gwas_search_extended(request):
    gwases = Gwasinfo.objects.all()
    chrs = ["chr1", "chr2", "chr3", "chr4", "chr5", "chr6","chr7", "chr8", "chr9","chr10", "chr11", "chr12",\
            "chr13", "chr14", "chr15","chr16", "chr17", "chr18","chr19", "chr20", "chr21","chrX", "chrY"]
    tfs = Tfs.objects.all()
    return render(request, 'draftapp/gwas_search_extended.html', {"gwases": gwases, "chrs": chrs, "tfs": tfs})

        


def gene_search(request):
    genes = Geneannotation.objects.all().values('genesymbol', 'geneid')
    return render(request, 'draftapp/gene_search.html', {"genes": genes})


def gene_query(query):
    no_hits = []#genes for which no coresponding snps etc are found
    hits = []#successfull genes
    genes = Geneannotation.objects.filter(Q(genesymbol__in = query) | Q(geneid__in = query)).values("genesymbol", "geneid")
    gene_dict= {}
    for gene in genes:
        snps = Snps.objects.filter(Interactions_gene_snps_rsid__geneid__genesymbol__exact = gene["genesymbol"]).distinct().values("rsid", "chr", "start", "end")
        if snps: 
            hits.append(gene["genesymbol"])
            snps_rsid = [rsnp["rsid"] for rsnp in snps]
            tfs = Tfsxsnps.objects.filter(Q(rsid__in = snps_rsid)).distinct().values("tfid", "rsid", "efoid")
            exs = Interactionsxgenexsnps.objects.filter(Q(rsid__in = snps_rsid)).distinct().values("enhancerid", "rsid")
            list_per_gene =  []
            for  snp in snps:
                tf_list = [tf["tfid"] for tf in tfs if tf["rsid"] == snp["rsid"]]
                tf_string = ", ".join(tf_list)
                gwas_list = [tf["efoid"] for tf in tfs if tf["rsid"] == snp["rsid"]]
                gwases = Gwasinfo.objects.filter(Q(efoid__in = gwas_list)).distinct().values("name", "efoid")
                gwas_name_list = [gwas["name"] for gwas in gwases]
                efoid_list = [gwas["efoid"] for gwas in gwases]#I think this might be necessary to keep the order
                gwas_string = ", ".join(gwas_name_list)
                #efoid_string = ", ".join(efoid_list)
                exs_list = [ex["enhancerid"] for ex in exs if ex["rsid"] == snp["rsid"]]
                exs_string = ", ".join(exs_list)
                list_per_gene.append([snp["rsid"], snp["chr"]+":"+str(snp["start"])+"-"+str(snp["end"]), tf_string, gwas_string,\
                                    exs_string, efoid_list])
            gene_info = gene["genesymbol"]+", "+gene["geneid"]
            gene_dict[gene_info] = list_per_gene
        else:
            no_hits.append(gene["genesymbol"]+" (" + gene["geneid"] + ")")  
    return gene_dict, hits, no_hits   
            
def gene_search_results_snps(request):
    if request.method == 'GET':
        query = request.GET.getlist('genes[]')
        if query:
            gene_dict, hits, no_hits = gene_query(query)
            no_hits = ", ".join(no_hits)
            hits = ", ".join(hits)
            return render(request, 'draftapp/gene_search_results_snps.html', {'gene_dict': gene_dict, "no_hits": no_hits, "hits": hits})
        else:
            raise Http404("The given gene cannot be found")
    else:
        raise Http404("No gene given")

def snp_search(request):
    snps = Snps.objects.all()
    return render(request, 'draftapp/snp_search.html', {"snps": snps})

class SnpsDetailView(generic.DetailView):
    model = Snps
    template_name = 'draftapp/snps_detail.html' 

def snp_search_results(request):
    if request.method == 'GET':
        snps = request.GET.getlist('snps[]')
        snps_objects = Snps.objects.filter(rsid__in = snps).distinct().values("rsid", "start", "chr", "end")
        snps_rsid = [rsnp["rsid"] for rsnp in snps_objects]
        tfsxsnps = Tfsxsnps.objects.filter(Q(rsid__in = snps_rsid)).distinct().values("id", "rsid", "tfid", "allele1", "allele2",\
                                                                                      "strand", "posinmotif", "diffbindpvalue", "adjustedpvalue")
        tfsxsnps_rsid = list(set([tfsxsnp["rsid"] for tfsxsnp in tfsxsnps]))
        no_hits = list(set([snp for snp in snps if snp not in tfsxsnps_rsid]))
        no_hits = ", ".join(no_hits)
        exs = Interactionsxgenexsnps.objects.filter(Q(rsid__in = snps_rsid)).distinct().values("enhancerid", "rsid", "geneid")
        geneids = list(set([ex["geneid"]for ex in exs]))
        genes = Geneannotation.objects.filter(geneid__in = geneids).values("geneid", "genesymbol")
        snp_query = {}
        for tfsxsnp in tfsxsnps:
            snp_position = [snp["chr"]+":"+str(snp["start"])+"-"+str(snp["end"]) for snp in snps_objects if snp["rsid"] == tfsxsnp["rsid"]]
            snp_position = snp_position[0]
            interactions = ", ".join([ex["enhancerid"]for ex in exs if ex["rsid"] == tfsxsnp["rsid"]])
            if not interactions:
                interactions = "Unknown"
            linked_genes = [ex["geneid"]for ex in exs if ex["rsid"] == tfsxsnp["rsid"]]
            if not linked_genes:
                linked_geneids = "Unknown"
                linked_genenames = "Unknown"
            else:
                linked_genenames = [gene["genesymbol"] for gene in genes if gene["geneid"] in linked_genes]
                linked_genenames = ", ".join(linked_genenames)
                linked_geneids = ", ".join(linked_genes)

            snp_query[tfsxsnp["id"]] = [tfsxsnp["rsid"], snp_position, tfsxsnp["tfid"], tfsxsnp["allele1"], tfsxsnp["allele2"],\
                                        tfsxsnp["strand"], tfsxsnp["posinmotif"], tfsxsnp["diffbindpvalue"], tfsxsnp["adjustedpvalue"],\
                                              interactions, linked_geneids, linked_genenames]
    return render(request, 'draftapp/snps_query_results.html', {"tfxsnps": snp_query, "no_hits":no_hits})

 
 

 


def make_snp_dict_helper_2(snps_unique, snp_dict, trans_fac, gwas):
    snps = [rsnp["rsid"] for rsnp in snps_unique]
    if trans_fac:
        tfs = Tfsxsnps.objects.filter(Q(tfid__name__in = trans_fac)& Q(rsid__rsid__in = snps)& Q(efoid__efoid__name__exact = gwas)).distinct().values("tfid", "rsid")
    else:
        tfs = Tfsxsnps.objects.filter(Q(rsid__rsid__in = snps)& Q(efoid__efoid__name__exact = gwas)).distinct().values("tfid", "rsid")
    exs = Interactionsxgenexsnps.objects.filter(rsid__rsid__in = snps).values("enhancerid", "rsid", "geneid")
    gene_ids_for_filter = [ex["geneid"] for ex in exs]
    gene_annos = Geneannotation.objects.filter(Q(geneid__in = gene_ids_for_filter )).values("geneid", "genesymbol")
    for snp in snps_unique:
        snp_dict[snp["rsid"]] = [snp["chr"]+":"+str(snp["start"])+"-"+str(snp["end"]),"", "", "", ""]
        snp_dict[snp["rsid"]][1] = ", ".join([tf["tfid"] for tf in tfs if tf["rsid"] == snp["rsid"]])
        geneids = [ex["geneid"] for ex in exs if ex["rsid"] == snp["rsid"]]
        genes = [gene_anno["genesymbol"] for gene_anno in gene_annos if gene_anno["geneid"] in geneids]
        snp_dict[snp["rsid"]][2] = ", ".join([geneid for geneid in geneids])
        snp_dict[snp["rsid"]][3] = ", ".join([genename for genename in genes])
        snp_dict[snp["rsid"]][4] = ", ".join([ex["enhancerid"] for ex in exs if ex["rsid"] == snp["rsid"]])
        
            
        
    for snp, info in snp_dict.items():
        if info[1] == "":
            snp_dict[snp][1] = "Unknown"
        if info[4] == "":
            snp_dict[snp][2]  = "Unknown"
            snp_dict[snp][3]  = "Unknown"
            snp_dict[snp][4]  = "Unknown"
    return snp_dict

def get_snp_dict(gwas, tf, chromosome):
    if gwas:
        gwas_info = Gwasinfo.objects.filter(Q(name__in = gwas) | Q(efoid__in = gwas)).distinct().values("name", "efoid")
        snp_dict_complete = {}
        for gwas_trait in gwas_info:
            snp_dict = {}
            if tf and chromosome:
                snps_unique = Snps.objects.filter(Q(Tfsxsnps_rsId__efoid__efoid__name__exact = gwas_trait["name"]) & \
                                                    Q(Tfsxsnps_rsId__tfid__name__in = tf) & Q(chr__in = chromosome)).distinct()\
                                                        .values("rsid", "chr", "start", "end")
                snp_dict = make_snp_dict_helper_2(snps_unique, snp_dict, tf, gwas_trait["name"])    
            elif chromosome:
                snps_unique = Snps.objects.filter(Q(Tfsxsnps_rsId__efoid__efoid__name__exact = gwas_trait["name"]) & \
                                                    Q(chr__in = chromosome)).distinct()\
                                                        .values("rsid", "chr", "start", "end")
                snp_dict = make_snp_dict_helper_2(snps_unique, snp_dict, tf, gwas_trait["name"])
            elif tf:
                snps_unique = Snps.objects.filter(Q(Tfsxsnps_rsId__efoid__efoid__name__exact = gwas_trait["name"]) & \
                                                    Q(Tfsxsnps_rsId__tfid__name__in = tf)).distinct()\
                                                        .values("rsid", "chr", "start", "end")
                
                snp_dict = make_snp_dict_helper_2(snps_unique, snp_dict, tf, gwas_trait["name"])
            else:
                snps_unique = Snps.objects.filter(Q(Tfsxsnps_rsId__efoid__efoid__name__exact = gwas_trait["name"])) \

draf2/draftapp/templates/draftapp/base.html
<!DOCTYPE html>
<html>
<meta charset="UTF-8">
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<!-- loads the path to your static files -->
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'draftapp/style.css' %}" />
{% block title%}
<title>SNEEP</title>
{% endblock %}

<body>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e4e9e9; width:120%">
    <div class="container-fluid">
      <a class="navbar-brand" href="">SNEEP</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'draftapp:index' %}">SNEEP overview</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Queries
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'draftapp:gwas_search_extended'%}">GWAS trait search</a></li>
              <li><a class="dropdown-item" href="{% url 'draftapp:gene_search'%}">Gene search</a></li>
              <li><a class="dropdown-item" href="{% url 'draftapp:snp_search'%}">SNP search</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'draftapp:REST_API' %}">REST API</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {% block body%}
  {% endblock %}




</body>

</html>

draf2/draftapp/templates/draftapp/base_snp_results.html
<!DOCTYPE html>
<html>
<meta charset="UTF-8">
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<!-- loads the path to your static files -->
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'draftapp/style.css' %}" />
{% block title%}
<title>SNEEP</title>
{% endblock %}

<body>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e4e9e9; width:120%">
    <div class="container-fluid">
      <a class="navbar-brand" href="">SNEEP</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'draftapp:index' %}">SNEEP overview</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Queries
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'draftapp:gwas_search_extended'%}">GWAS trait search</a></li>
              <li><a class="dropdown-item" href="{% url 'draftapp:gene_search'%}">Gene search</a></li>
              <li><a class="dropdown-item" href="{% url 'draftapp:snp_search'%}">SNP search</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'draftapp:REST_API' %}">REST API</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {% block body%}
  {% endblock %}




</body>

</html>

draf2/draftapp/templates/draftapp/gene_search.html
{% extends "draftapp/base.html" %}
{% block body%}
{% load static %}

<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/habibmhamadi/multi-select-tag/dist/css/multi-select-tag.css">
<script src="{% static 'js/multiselect_new.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/PapaParse/4.1.2/papaparse.min.js"></script>

<div class="container">
  <div class="row h-200">
    <div class="col-12">
      <h4>Enter a gene to find associated rSNPs:</h4>
    </div>
    <div class="row input-group"
      title="Only the top20 gene hits are shown as options, if your gene of interest is not there, try to type more letters.">
      <form action="{% url 'draftapp:gene_search_results'%}" method="get" class="d-flex" role="search">



        <div class="col-4">
          <select name="genes[]" id="genes" class="genes" multiple>
            <option value="EBF1" id="EBF1" label="EBF1"> </option>
            <option value="OGFOD2" id="OGFOD2" label="OGFOD2"> </option>
          </select>
        </div>

        <div class="col-md">
          <button class="btn d-flex" style="background-color: #00CED1;" type="submit">Search</button>
      </form>
    </div>



    <div class="col-10 float-right">
      <ul id="gene_list">
      </ul>
    </div>
  </div>
</div>
<div class="row h-100 mt-5">
  <div class="col-md">
    <h4>Or enter a .txt file of genes:</h4>
    The file should have one gene per line.
  </div>
</div>
<div class="row h-100 mt-5">
  <div class="col-md">
    <input type="file" accept=".txt, .csv" id="gene_file">
  </div>



</div>
</div>


<div class="col-2 align-self-start">
  <button class="exemplary_query btn btn-light btn-outline-dark col-xs-2 text-left" style="background-color: #e3e6e6;"
    id="exemplary_query" onclick="exemplaryGeneQuery()">Example
    Query</button>
</div>


<script>
  new MultiSelectTag('genes', {
    rounded: true,    // default true
    shadow: true,      // default false
    input_id: "gene_input",
    list_id: "gene_options",
    container_id: "gene_container",
    multiselect_id: "gene_multi",
    placeholder: 'genes',
  })
</script>



<script>
  $(function () {
    var availableTags = [
      {% for gene in genes %}
            "{{gene.genesymbol}}",
    {% endfor %}
    {% for gene in genes %}
  "{{gene.geneid}}",
    {% endfor %}
    ];

  $("#gene_input").autocomplete({
    source: function (request, response) {
      var results = $.ui.autocomplete.filter(availableTags, request.term);
      let gene_options = results.slice(0, 20);
      console.log(gene_options);
      let gene_opt = [];
      gene_options.forEach((gene, index) => {
        if (index >= 0) { let ge = {}; ge.value = gene, ge.label = gene; gene_opt.push(ge) }
      });
      new updateMultiSelectTag('genes', gene_opt, {
        rounded: true,    // default true
        shadow: true,      // default false
        ul_name: 'gene_options',
        input_container_id: "gene_container",
        input_id: "gene_input"
      });
    }
  });
  });


</script>

<script>
  let gene_list = [];
  document.getElementById('gene_file').addEventListener('change', upload, false);
  function upload(evt) {
    var data = null;
    var file = evt.target.files[0];
    var reader = new FileReader();
    reader.readAsText(file);
    reader.onload = function (event) {
      var csvData = event.target.result;
      var results = Papa.parse(csvData);
      for (const array of results["data"]) {
        gene_list = gene_list.concat(array);
      };
      console.log(gene_list);
      let gene_opt = [];
      gene_list.forEach((gene, index) => { if (index >= 0) { let ge = {}; ge.value = gene, ge.label = gene, ge.selected = "selected"; gene_opt.push(ge) } });
      new updateMultiSelectTag('genes', gene_opt, {
        rounded: true,    // default true
        shadow: true,      // default false
        ul_name: 'gene_options',
        input_container_id: "gene_container",
        input_id: "gene_input"
      });
    };
    reader.onerror = function () {
      alert('Unable to read ' + file.fileName);
    };
  };
</script>



<script>function exemplaryGeneQuery() {
    $('#genes').val(["OGFOD2", "EBF1"]);
    location.reload();
  }
</script>



<style>
  .exemplary_query:hover,
  .exemplary_query:focus,
  .exemplary_query:active,
  .exemplary_query.active,
  .open>.dropdown-toggle.exemplary_query {
    color: #fff !important;
    background-color: #063944 !important;
    border-color: #063944 !important;
    /*set the color you want here*/
  }


  .container {
    max-width: 1700px;
  }

  .gene_button {
    background: #CCFFFF;

  }

  .btn-group {
    border: #1df5f5;
  }
</style>

{% endblock %}

draf2/draftapp/templates/draftapp/gene_search_results_snps.html
{% extends "draftapp/base.html" %}
{% block body%}
{% load filter_tags %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css" />
<script type="text/javascript" src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>



<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.3.6/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.html5.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.print.min.js"></script>


<script type="text/javascript">
  $(document).ready(function () {
    $('#table').DataTable({
      dom: 'Bfrtip',
      buttons: [
            { extend: 'copy', className: 'btn btn-light btn-outline-dark'},
            { extend: 'excel', className: 'btn btn-light btn-outline-dark' },
            { extend: 'csv', className: 'btn btn-light btn-outline-dark' }, 
            { extend: 'pdf', className: 'btn btn-light btn-outline-dark' },
            { extend: 'print', className: 'btn btn-light btn-outline-dark' }
      ],
    });
    lengthMenu: [
      [10, 25, 50, -1],
      [10, 25, 50, 'All'],
    ];
  });
</script>


{% if gene_dict %}
<h4>Gene query results:</h4>

<h5>For the following genes no match in the SNEEP database was found: {{ no_hits }}</h5>
<h5>The following genes were found in the SNEEP database and the results are shown in the table below: {{ hits }}
  <p>&nbsp;</p>
</h5>
<table id="table" class="table table-bordered">
  <thead class="alert-success">
    <tr>
      <th>Gene name</th>
      <th>Ensembl id</th>
      <th>associated rSNP</th>
      <th>rSNP position</th>
      <th>GWAS traits associated to rSNPs</th>
      <th>efoIDs of GWAS traits</th>
      <th>Enhancers</th>
      <th>Transcription factors</th>

    </tr>
  </thead>
  <tbody>

    {% for gene, list_per_gene in gene_dict.items %}
    {% for snp_list in list_per_gene %}
    <tr>
      {% with gene|split:", " as geneInfo %}
      <td>{{geneInfo.0}}</td>
      <td>{{geneInfo.1}}</a></td>
      {% endwith %}
      <td><a href="{% url 'draftapp:snp_detail' snp_list.0 %}">{{snp_list.0}}</a></td>
      <td>{{snp_list.1}}</td>
      <td>{{snp_list.3}}
      </td>
      <td>{% for efoid in snp_list.5%}
        <a href="https://www.ebi.ac.uk/gwas/efotraits/{{efoid}}">{{efoid}}</a>
        {% endfor %}
      </td>
      <td>{{snp_list.4}}
      </td>
      <td>{{snp_list.2}}
      </td>
    </tr>

    {% endfor %}
    {% endfor %}
  </tbody>
</table>




{% else %}
<h3>This Gene is not investigated by us!</h3>
{% endif %}


{% endblock %}

draf2/draftapp/templates/draftapp/index.html
{% extends "draftapp/base.html" %}
{% block body%}
{% load static %}
<div class="container mt-5">
  <div class="row">
    <div class="col-4" style="text-align: center;">
      <h4>SNEEP: How is transcription factor binding activity influenced by genetic variants?
      </h4>
    </div>
    <div class="col-8 text-center">
      <h4>Explore the query options for SNEEP:</h4>
    </div>
  </div>

  <div class="row">
    <div class="col-4" style="text-align: justify;">
      Regulatory single nucleotide polymorphisms (rSNPs) are predominantly found in non-coding regions. These changes of
      one base in the DNA
      can influence the binding affinity of transcription facotrs and with that the gene expression of target genes.
      SNEEP links rSNPs to the TFs influenced...
    </div>


    <div class="col">
      <button class="btn btn-secondary inline-button btn-flex" style="background-color: #e4e9e9;">
        <a href="{% url 'draftapp:gene_search' %}" class="btn" style="background-color: #e4e9e9;" role="button">
          <p><img class='img-fluid' src="{% static 'draftapp/images/dna-47643.png' %}" alt='GeneQuery' /></p>
          <span>
            <h5> Gene query </h5>
        </a></span>
      </button>
    </div>

    <div class="col">
      <button class="btn btn-secondary inline-button btn-flex" style="background-color: #e4e9e9;">
        <a href="{% url 'draftapp:gwas_search_extended' %}" class="btn" style="background-color: #e4e9e9;"
          role="button">
          <p><img class='img-fluid' src="{% static 'draftapp/images/GWAQuery.png' %}" alt='GwasQuery' /></p>
          <span>
            <h5>GWAS query</h5>
        </a></span>
      </button>
    </div>

    <div class="col">
      <button class="btn btn-secondary inline-button btn-flex" style="background-color: #e4e9e9;">
        <a href="{% url 'draftapp:snp_search' %}" class="btn" style="background-color: #e4e9e9;" role="button">
          <p><img class='img-fluid' src="{% static 'draftapp/images/Mein Projekt.png' %}" alt='SNPQuery' /></p>
          <span>
            <h5>SNP query </h5>
          </span>
        </a>
      </button>
    </div>
  </div>
</div>

<style>
  *:focus {
    border: none !important;
    outline: none !important;
    box-shadow: none !important;
  }
</style>
{% endblock %}